name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, redis, pdo_mysql
        coverage: pcov

    - name: Start MySQL service
      run: sudo /etc/init.d/mysql start

    - name: Verify MySQL connection
      run: mysql --version

    - name: Install PHPUnit
      run: |
        wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
        chmod +x phpunit
        ./phpunit --version

    - name: Run tests
      run: ./phpunit
